### ISSUE TITLE
Düzenlemeler

### ISSUE THREAD

**Issue by krmgns** [craftgate/craftgate-opencart-3.x-gateway#1]
Bir iki konuya değinmek istiyorum, görebildiğim kadarıyla; Mesela formatPrice() yöntemi float yenine bool veri ile çağrılmış (1). Zaten PHP'de float veri karşılaştırmalarının "$x != 0" şeklinde yapılması tavsiye edilmez. Orada "$x > 0.0" demek daha uygun görünüyor. Diğer gözüme çarpan şey ise and/or ifadelerinin uyumsuzluğu (2), yani wrap edilmemiş parantezlerle, bu da her daim dengesiz bir bool sonuç verecektir. Yanı sıra çoğu yerde cast'lar yapılmamış (3), bilhassa sayısal verilerle çalışırken "$x = (float) $x" şeklinde cast kullanımı tavsiye edilir, hem güvenlik hem de veri tutarlılığı açısından. Bir de İyzico şeysi görüyorum (4), sanırım orada da başka bir yanlışlık olmuş.

Kanımca paketin, ehil bir PHP Dev. ile sıkı bir revizeden geçirilmesi daha sağlıklı ilerlemenizi sağlayacaktır.

1. https://github.com/craftgate/craftgate-opencart-3.x-gateway/blob/master/upload/catalog/controller/extension/payment/craftgate_payment_gateway.php#L145
2. https://github.com/craftgate/craftgate-opencart-3.x-gateway/blob/master/upload/catalog/controller/extension/payment/craftgate_payment_gateway.php#L240 ve https://github.com/craftgate/craftgate-opencart-3.x-gateway/blob/master/upload/catalog/controller/extension/payment/craftgate_payment_gateway.php#L250.
3. https://github.com/craftgate/craftgate-opencart-3.x-gateway/blob/master/upload/catalog/controller/extension/payment/craftgate_payment_gateway.php#L35
4. https://github.com/craftgate/craftgate-opencart-3.x-gateway/blob/master/upload/catalog/model/extension/payment/craftgate_payment_gateway.php#L42

Şuraya bir şeyler bırakıyorum, dilerseniz kullanabilirsiniz.
Kolay gelsin.

https://gist.github.com/k-gun/43a1c26f49be17d44d8012c44ae94a3e

**Comment by sotuzun** [comment]
@k-gun Selamlar teşekkürler desteğin için. İnceleyelim hemen.

**Comment by sotuzun** [comment]
Gerekli düzenlemeleri yaptık @k-gun teşekkürler.
